"""Added nullable to some columns of user rooms tables

Revision ID: 2fba81ed980f
Revises: 503df7bb4ab5
Create Date: 2024-11-07 20:07:20.809895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fba81ed980f'
down_revision: Union[str, None] = '503df7bb4ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
