"""Added nullable to some columns of user rooms tables

Revision ID: 503df7bb4ab5
Revises: 16ee7d180fe8
Create Date: 2024-11-07 19:55:03.380191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503df7bb4ab5'
down_revision: Union[str, None] = '16ee7d180fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
